### ISSUE TITLE
App pulling an old or alternate reach name

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#196]
Note that the app uses the AKA Section 1 name for the [Rock Gorge of the Chattooga](https://www.americanwhitewater.org/content/River/view/river-detail/1049/main). Both should use the primary reach name.

**Comment by AWKevin** [comment]
Note Great Falls Catawba Short Channel in SC is the same issue. 

![Screen Shot 2021-07-22 at 1 28 28 PM](https://user-images.githubusercontent.com/7936679/126683969-ab4139d7-5dcc-442a-b138-7d2fa066e4f6.png)


![IMG_5904](https://user-images.githubusercontent.com/7936679/126684002-f61f906b-488b-413b-a3c9-76c2fcb45c9c.jpg)

**Comment by Gregliest** [comment]
Fixed by https://github.com/AmericanWhitewater/aw-ios/pull/250

**Comment by AWKevin** [comment]
This is not fixed yet. The Chattoog rock gorge still says "AKA Section 1" and the Great Falls Short Channel still says "Great Falls"

The App is pulling the "Alternate Name" instead of "Reach Name." @ryangroth5 can you offer any insight into the API endpoints for these fields.

**Comment by Gregliest** [comment]
@AWKevin This is fixed for me. I'll bet if you reinstalled the app it would show correctly. However, it would be good to know why this isn't changing for you. Can you try the following in order until the issue goes away?

1. Refresh the run list
2. Change your filters to some other region
3. Close the app completely (with the swipe up)
4. Reinstall the app

Interested to see if any of those work.
